name: Sign In
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2,3,6,7,8,9,10 * * *'

jobs:
  schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: 
        run: pnpm run:main
        env:
           GITHUB_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
           DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}